### ISSUE TITLE
Incorrect library version

### ISSUE THREAD

**Issue by imciner2** [mhogomchungu/lxqt_wallet#33]
The library version defined in the CMake file is 3.2.0, but the latest release is 3.2.1. This means that distro packaging ships a version of lxqt-wallet that is versioned as 3.2.1 but shows up to dependent packages in the configure stage as 3.2.0.

**Comment by mhogomchungu** [comment]
This is intentional.

1. Library version of 3.0.0 was because of API change[1].
2. Library version of 3.1.0 was also because of API change[2].
3. Library version of 3.2.0 was also because of API change[3].
4. Package version 3.2.1[4] is not accompanied with API change and that is the library version stayed at version 3.2.0

What is the proper way of managing package version and library version if they are not always in sync?

[1] https://github.com/lxqt/lxqt_wallet/releases/tag/3.0.0

[2] https://github.com/lxqt/lxqt_wallet/releases/tag/3.1.0

[3] https://github.com/lxqt/lxqt_wallet/releases/tag/3.2.0

[4] https://github.com/lxqt/lxqt_wallet/releases/tag/3.2.1

**Comment by imciner2** [comment]
The expectation is that the library would say it is at version 3.2.1 for release 3.2.1 - even if the API doesn't change (that is the principle behind patch releases in semver: https://semver.org/). The version reported by the library should be the exact version of the library - otherwise how will someone know if they are on patch release 3.2.1 or the future 3.2.2, etc.?

**Comment by mhogomchungu** [comment]
New release fixed this issue: https://github.com/lxqt/lxqt_wallet/releases/tag/3.2.2

**Comment by imciner2** [comment]
Thanks!
