### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by shlyakpavel** [mhogomchungu/lxqt_wallet#9]
https://github.com/mhogomchungu/lxqt_wallet/blob/370add9e5959a2db19cebce02338df36d8cb08aa/frontend/changepassworddialog.cpp#L61
Could you please explain me the magic of this code? It would be really nice to have a comment there as it's not obvious (imo)

**Comment by mhogomchungu** [comment]
I want to be notified whenever a window is closed and this[1][2] overridden method is not called when a user press the escape key(unexpected behavior) and the window just disappears(expected behavior).  The method does get called when the user press the close button on the window's title bar.

This behavior was there when i wrote the code in Qt4 days and i am not sure if its still relevant but it was back then.

[1] https://github.com/mhogomchungu/lxqt_wallet/blob/370add9e5959a2db19cebce02338df36d8cb08aa/frontend/changepassworddialog.cpp#L302

[2] https://doc.qt.io/qt-5/qwidget.html#closeEvent

**Comment by mhogomchungu** [comment]
Just tried with Qt 5.12.4 and the behavior is still there.

The closeEvent method is called when the user press the close button on the title bar and the window disappears.

With the code removed, the window just disappears but the closeEvent method is never called when the user press the escape key while the window is active.

**Comment by shlyakpavel** [comment]
@mhogomchungu thank you for explaining! It would be also great to have a comment in the code to avoid confusions :)

**Comment by mhogomchungu** [comment]
done[1]

[1] https://github.com/mhogomchungu/lxqt_wallet/commit/a14822705c5a2233da9fbf41138b6124c97efce1
